#
# more information can be found here http://sonata-project.org/bundles/user
#
# Enable Doctrine to map the provided entities
sonata_user:    
    security_acl: true
    manager_type: orm # can be orm or mongodb
    admin:                  # Admin Classes
        user:
            class:          Application\Sonata\UserBundle\Admin\UserAdmin # there define your extended admin class
            controller:     SonataUserBundle:UserAdmin
        group:
            class:          Application\Sonata\UserBundle\Admin\GroupAdmin
            controller:     SonataUserBundle:GroupAdmin        	    
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataUserBundle: ~
                    SonataUserBundle: ~                                
     