<?php

namespace AppBundle\Repository;

//use Doctrine\ORM\EntityRepository;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * OrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * Extends NestedTreeRepository to support tree features 
 */
class OrganizationRepository extends NestedTreeRepository
{    
}
